// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsS_qr4XtBfuqLH2VtJnmtXDXqcKQtbfY',
    appId: '1:715548714374:web:8bd1d6000a6e03593ff807',
    messagingSenderId: '715548714374',
    projectId: 'apotik-260ed',
    authDomain: 'apotik-260ed.firebaseapp.com',
    storageBucket: 'apotik-260ed.firebasestorage.app',
    measurementId: 'G-VK9HDYH2CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeGGHQiA9Ta8jeIznLEESB-4QqJrF3sx8',
    appId: '1:715548714374:android:cc1e2a472befabc83ff807',
    messagingSenderId: '715548714374',
    projectId: 'apotik-260ed',
    storageBucket: 'apotik-260ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyVrRtScFC3Jor39rYaMhLrnwC65NaVI',
    appId: '1:715548714374:ios:7e2b9b3187895d4b3ff807',
    messagingSenderId: '715548714374',
    projectId: 'apotik-260ed',
    storageBucket: 'apotik-260ed.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiPraktekUk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyVrRtScFC3Jor39rYaMhLrnwC65NaVI',
    appId: '1:715548714374:ios:7e2b9b3187895d4b3ff807',
    messagingSenderId: '715548714374',
    projectId: 'apotik-260ed',
    storageBucket: 'apotik-260ed.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiPraktekUk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsS_qr4XtBfuqLH2VtJnmtXDXqcKQtbfY',
    appId: '1:715548714374:web:f4e631b5a3a65b6f3ff807',
    messagingSenderId: '715548714374',
    projectId: 'apotik-260ed',
    authDomain: 'apotik-260ed.firebaseapp.com',
    storageBucket: 'apotik-260ed.firebasestorage.app',
    measurementId: 'G-X4V9MF5SPW',
  );
}
